name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    name: Test on python ${{ matrix.python-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version: [ 3.6.7, 3.6.10, 3.6.14, 3.7.5, 3.7.11, 3.8.0, 3.8.5, 3.9.0, 3.9.6, 3.9.18, 3.10.13, 3.11.6]

    steps:
    - uses: actions/checkout@v3
    - name: Use Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi

    - name: Run tests
      run: coverage run --source=json2html setup.py test
